# Generated by Django 5.2.8 on 2026-01-28 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advertiserad',
            index=models.Index(fields=['advertiser', 'is_active'], name='advertisers_adverti_2e493a_idx'),
        ),
        migrations.AddIndex(
            model_name='advertiserad',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='advertisers_is_acti_44e9dd_idx'),
        ),
    ]
