"""
Django settings for adwisegpt project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@lb1wq5inw8h(k65b#&9urq8k7p&rt39zdd&xqwhxt!ia4!&6_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',

    'django.contrib.staticfiles',
    
    'cloudinary',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',   # for logout blacklisting
    'accounts',
    'advertisers',
    'user',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'adwisegpt.urls'
CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adwisegpt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#databases 
DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        # 'NAME': 'adwisegpt_db',
        # 'USER': 'adwise_user',
        # 'PASSWORD': 'StrongPassword123!',
        # 'HOST': '127.0.0.1',
        # 'PORT': '3306'
        'NAME': config('NAME'),
        'USER':config('USER'),
        'PASSWORD':config('PASSWORD'),
        'HOST':config('HOST'),
        'PORT':config('PORT')
    }
}

REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework_simplejwt.authentication.JWTAuthentication',
  )
}



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Gmail SMTP settings
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
# EMAIL_HOST_USER = 'adwisegpt@gmail.com'  # replace with your Gmail
# EMAIL_HOST_PASSWORD = 'fwftwmnkukubkmek'  # see step 2
EMAIL_HOST_PASSWORD=config('EMAIL_HOST_PASSWORD')
EMAIL_HOST_USER=config('EMAIL_HOST_USER')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Admins list (used to notify)
ADMINS = [('Admin', 'adwisegpt@gmail.com')]

from datetime import timedelta
SIMPLE_JWT = {
  'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),
  'REFRESH_TOKEN_LIFETIME': timedelta(days=2),
  'AUTH_HEADER_TYPES': ('Bearer',),
}

#google login
#GOOGLE_CLIENT_ID = "177022522100-9je7n6jaapr7erv7sgtnagpg73arucvj.apps.googleusercontent.com"
GOOGLE_CLIENT_ID=config('GOOGLE_CLIENT_ID')



CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_API_KEY'),
    'API_SECRET': config('CLOUDINARY_API_SECRET'),
}

#DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# For Django 4.2, 5.0, 5.1+
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

#media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Your site URL (for callbacks)
SITE_URL = 'http://localhost:8000'  # Change in production




import os
FAISS_INDEX_DIR = os.path.join(BASE_DIR, 'faiss_store')

FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB


#models
#HUGGINGFACE_API_TOKEN = os.getenv('HUGGINGFACE_API_TOKEN', '')
HUGGINGFACE_API_TOKEN = config('HUGGINGFACE_API_TOKEN', default='')

# Pinecone Configuration
PINECONE_API_KEY = config('PINECONE_API_KEY')
PINECONE_INDEX_NAME = 'ad-retrieval-index'
PINECONE_ENVIRONMENT = 'us-east-1'
PINECONE_NAMESPACE = 'ad-retrieval'  # Optional: for multi-tenancy

GOOGLE_API_KEY = config('GOOGLE_API_KEY', default='')

TIME_ZONE = 'Asia/Karachi'  # Or your timezone
USE_TZ = True



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        # The empty string '' represents the ROOT logger.
        # This catches logs from ANY module that isn't specifically defined elsewhere.
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
    #exceptions
    'EXCEPTION_HANDLER': 'adwisegpt.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [],  # no global throttling — set per-view
    'DEFAULT_THROTTLE_RATES': {
        'chat_user':       '5/min',
        'chat_user_daily': '200/day',
        'ads_user':        '20/min',
        'new_chat':        '10/hour',
        'refresh_ads':     '5/min',
        'contact_anon':    '5/hour',

        #advertiser
        'ad_event_anon':    '60/min',   # impression/click tracking (public)
        'ad_click_anon':    '30/min',   # click redirect (public)
        'campaign_create':  '10/hour',  # campaign creation
        'submit_payment':   '5/hour',   # payment submission
        'analytics':        '30/hour',  # heavy analytics queries
        'dashboard':        '30/hour',

        #accounts
        'register':        '5/hour',
        'login':           '5/min',
        'resend_otp':      '3/hour',
        'password_reset':  '5/hour',
        'otp_confirm':     '10/hour',
        'google_auth':     '10/min',

    }

}

