# Generated by Django 5.2.8 on 2025-12-12 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complete_opt_out', models.BooleanField(default=False)),
                ('contextual_advertising', models.BooleanField(default=True)),
                ('ad_frequency', models.CharField(choices=[('MINIMAL', 'minimal'), ('BALANCED', 'balanced'), ('DISCOVERY', 'discovered')], default='BALANCED', max_length=10)),
                ('interest_categories', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
