# Generated by Django 5.2.8 on 2025-12-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='ad_frequency',
        ),
    ]
